package com.shopbilling.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_ENABLED,
    PASSWORD_RESET,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    VARIANT_CREATED,
    VARIANT_UPDATED,
    BARCODE_GENERATED,
    INVENTORY_UPDATED,
    INVOICE_CREATED,
    INVOICE_UPDATED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    REPORT_GENERATED,
    BACKUP_CREATED,
    BACKUP_RESTORED,
    SETTINGS_UPDATED,
    ITEM_RETURNED
}